services:
  - type: web
    name: bocao-lanches
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn bocao_lanches.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: bocao-lanches.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: bocao-lanches-db
          property: connectionString
    healthCheckPath: /

databases:
  - name: bocao-lanches-db
    databaseName: bocaolanches
    user: bocaolanches
    plan: free
